version: '3.3'
services:
  web:
      image: php:7.3-apache
      container_name: php_web
      environment: 
                  - ALLOW_OVERRIDE=true
      ports:
                  - "6000:80"
      links:
                  - db
      volumes:
                  - ./php:/var/www/html/
  db:
      container_name: mysql_web
      image: mariadb
      restart: always
      volumes:
                  - ./mysql:/var/lib/mysql
      environsment:
                  MYSQL_ROOT_PASSWORD: root
                  MYSQL_DATABASE: test_db
                  MYSQL_USER: regex
                  MYSQL_PASSWORD: regex123
      ports: 
                  - "3306:3306"
